// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using chefDishes.Models;

namespace chefDishes.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20181112220605_YourMigrationName")]
    partial class YourMigrationName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("chefDishes.Models.chef", b =>
                {
                    b.Property<int>("chefId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("age");

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("name");

                    b.Property<DateTime>("updatedAt");

                    b.HasKey("chefId");

                    b.ToTable("chef");
                });

            modelBuilder.Entity("chefDishes.Models.dishes", b =>
                {
                    b.Property<int>("DishesId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("calories");

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("name")
                        .IsRequired();

                    b.Property<int>("tastiness");

                    b.Property<DateTime>("updatedAt");

                    b.HasKey("DishesId");

                    b.ToTable("dishes");
                });
#pragma warning restore 612, 618
        }
    }
}
